### PR TITLE
Adding WatchKitSupport folder to zipped .ipa for WatchKit apps

### PR DESCRIPTION
**Pull request by fikeminkel**
If you attempt to submit an .ipa built using shenzhen that contains a WatchKit app the upload will succeed but you'll receive an error email from iTunes with this message:

Invalid WatchKit Support - The bundle contains an invalid implementation of WatchKit. The app may have been built or signed with non-compliant or pre-release tools. Visit developer.apple.com for more information.

This stackoverflow answer explains how to fix it:
http://stackoverflow.com/a/29400301/2418382

This pull request adds the necessary WatchKitSupport folder and WK binary so that the .ipa is valid.

### CODE REVIEW

**Comment by hjanuschka** [comment]
+1 nice one

**Comment by mattt** [comment]
Nice work, @fikeminkel. Thanks for your contribution.

**Comment by hjanuschka** [comment]
can you bump the version?

**Comment by sync** [comment]
since this fix got applied to 0.14.1, I am unable to submit a valid build to Apple iTunes connect, I don't have WatchKit support or a WatchKit target inside my app

if I use install this version of the gem `gem install shenzhen -v 0.14.0` it works without a problem

```
Dear developer,

We have discovered one or more issues with your recent delivery for "Yau Shop". To process your delivery, the following issues must be corrected:

Invalid WatchKit Support - The bundle contains an invalid implementation of WatchKit. The app may have been built or signed with non-compliant or pre-release tools. Visit developer.apple.com for more information.

Once these issues have been corrected, you can then redeliver the corrected binary.

Regards,

The App Store team
```

**Comment by hjanuschka** [comment]
updated to 0.14.1 and was able to submit an ipa build binary with WatchKit Target.

anyone knows - what happens if the WK support lib is copied - and no WatchKit target is available? maybe shenzhen needs an cmd flag "--watchkit" -  to only copy the support libs if --watchkit is enabled

**Comment by hjanuschka** [comment]
ok - rollback -  itc eats the binary - but cannot install on watch device.  "invalid watchkit binary"

**Comment by endoze** [comment]
I'm experiencing the same issue as @sync.

I don't have a WatchKit app or extension in my application. Every build I submit comes back with an invalid binary in iTunes Connect.

One other tidbit, I'm using [fastlane](https://github.com/krausefx/fastlane)'s [deliver](https://github.com/KrauseFx/deliver) tool which in turn pulls in version `0.14.1` of this gem.

I've gotten around this issue by using `bundle open shenzhen` and commenting out the WatchKit lines from this pull request. This is definitely not a permanent solution but it's gotten me around the issue until it can be resolved and a new version is released.

**Comment by endoze** [comment]
@sync @hjanuschka I've created a pull request that adds a flag to the build command to conditionally enable WatchKit support on #264. This should allow apps that don't have WatchKit apps/extensions to build properly for iTunes Connect.

**Comment by robwithhair** [comment]
Would be great this could get released.  We can't run our build scripts until this works unfortunately.

**Comment by frranck** [comment]
Same problem, when is this released ?

**Comment by robwithhair** [comment]
Just as a note I found that fastlane tools worked ok when uninstalling shenzhen and fastlane, and installing with -v option to specify version shenzhen 0.14.0 and fastlane 0.13.0.  gem clean was required.

**Comment by KrauseFx** [comment]
@robwithhair I updated something over here: https://github.com/nomad/shenzhen/pull/264?w=true

**Comment by KrauseFx** [comment]
Okay, I published a short comment about the current status: https://github.com/nomad/shenzhen/pull/264#issuecomment-100183533

There is an easy way to use a fixed version of `shenzhen` now :+1:

**Pull request merged**
