### PR TITLE
Include the ability to upload multiple dSYM files.

### PR DESCRIPTION
**Pull request by Noreaster76**
/cc @stepanhruda

### CODE REVIEW

**Comment by stepanhruda** [comment]
When using dynamic frameworks in Xcode 6, .framework has a separate binary with its own symbols. .xcarchive contains all necessary .dSYMs, so we should upload them so crash logs can be symbolicated correctly.

This PR doesn't touch testflight.rb, because TestFlight will be shutting down (couldn't find a public statement to link to, but I'm sure y'all got the email).

**Comment by stepanhruda** [comment]
We also enhanced this so you can only upload a .dSYM.zip file (or files), without the need to upload an .ipa. This is handy for App Store builds and it's done via the `--noIpa` option.

This allows you to automate uploading the .ipa to iTunes Connect and .dSYM.zip to HockeyApp at the same time.

**Comment by Mazyod** [comment]
+1, but seems to have merge conflicts. Wondering if this will be accepted, as well

**Comment by stepanhruda** [comment]
Will rebase/upmerge this when we have some time. What would you consider a blocker for acceptance? Feel free to comment on the diff.

**Comment by stepanhruda** [comment]
Refactored the code a bit and resolved conflicts. This is now ready for review.

**Pull request closed without merging**
