### PR TITLE
Add WatchKit conditional support

### PR DESCRIPTION
**Pull request by endoze**
In order to fix an issue where applications without WatchKit apps and
extensions would be marked as 'Invalid Binary' in iTunes Connect, this
commit wraps the WatchKit support setup in a conditional that checks for
WatchKit support in the project's plists.

### CODE REVIEW

**Comment by hjanuschka** [comment]
+1 for that - awesome!!!
you think there is a way to detect watchkit requirement, finding the "WatchKit App = TRUE" in the WatchKitApp plist file

**Comment by KrauseFx** [comment]
It is possible to automatically detect the WatchKit support:

The `path` is a path to the `plist` file.
```ruby
watchkit_enabled = `/usr/libexec/PlistBuddy -c 'Print WKWatchKitApp' '#{path}'`.strip
next if watchkit_enabled == 'true'
```
What I did is to iterate through all `plist` files inside the `.app` container. If only one of them as `watchkit_enabled`, I count it as WatchKit app.

**Comment by endoze** [comment]
@krausefx I'll update my pull request with this change instead of a flag.

**Comment by KrauseFx** [comment]
I'd be okay with the flag as well. I'm running into the same issue.

Basically, everybody using the latest version of `shenzhen` without a watch kit app will get an `invalid` binary message on iTunes Connect. 

@mattt Please let us know what you think. That's quite an urgent issue.

**Comment by zephyr-dev** [comment]
+1

**Comment by DenHeadless** [comment]
@KrauseFx  +1, dealing with this as well.

Easiest way right now is to install fastlane -v 0.13.0, uninstall shenzhen 0.14.1 and install shenzhen 0.14.0. 

Then everything will work just fine. Of course this needs to be fixed somehow, since fastlane 1.0.0 is unusable right now.

**Comment by KrauseFx** [comment]
@DenHeadless:
In the mean time, I pushed a [new version of fastlane](https://github.com/KrauseFx/fastlane/releases/tag/1.0.1) that uses the previous version of `shenzhen` until this issue is resolved.

Let me know if that works for you.

**Comment by DenHeadless** [comment]
@KrauseFx Thank you, you are lightning fast! :beers:

**Comment by KrauseFx** [comment]
@DenHeadless Thanks! :rocket: did it work for you? It's working fine for me, but one user reported he's still experiencing this issue.

**Comment by DenHeadless** [comment]
@KrauseFx Sorry, i'm not able to test it right now, our next demo will be only next week... But i see no reason it shouldn't work.

I uploaded build yesterday with fastlane 0.13.0 and shenzhen 0.14.0 and everything was good. So since this is shenzhen issue, not fastlane - everything should be fine.

**Comment by KrauseFx** [comment]
@DenHeadless Okay, great. I'm confident we'll fine a good solution until next week :+1:

**Comment by KrauseFx** [comment]
I forked `shenzhen` and added automatic Apple Watch detection: https://github.com/fastlane/shenzhen
with this commit: https://github.com/fastlane/shenzhen/commit/7286485bd974b5a38aba65b7729f32ba597a9f1a

I'm doing a hotfix release of fastlane, using `krausefx-shenzhen` until this issue is resolved :+1:

**Comment by robwithhair** [comment]
Well done @KrauseFx.  Good plan.

**Comment by KrauseFx** [comment]
I pushed a [new version](https://github.com/KrauseFx/fastlane/releases/tag/1.0.2) of `fastlane` now temporary using [krausefx-shenzhen](https://github.com/fastlane/shenzhen)

The code to automatically detect a WatchKit app is available here: https://github.com/fastlane/shenzhen/commit/7286485bd974b5a38aba65b7729f32ba597a9f1a. @endoze do you update your pull request or should I prepare a new one?

**Comment by hjanuschka** [comment]
awesome!

**Comment by robwithhair** [comment]
Thank you @KrauseFx!  A good solution to a difficult problem.

**Comment by endoze** [comment]
@KrauseFx I've rewritten my commit to detect watch kit support automatically and removed the build flag in 8fa5ea3.

**Comment by KrauseFx** [comment]
@endoze Thanks! Your code is much more Ruby like, I'll use that in `snapshot` as well :+1:

**Comment by mattt** [comment]
Excellent work, @endoze. Apologies for the delay in getting this merged. This is live in the latest version.

**Comment by endoze** [comment]
@mattt Thanks!

**Comment by AliAyasrah** [comment]
hello 

i am trying to build i always getting an error, this is what i did : 
$ cd to my project, than $ ipa build 

i got this : 
     xcodebuild  Watch.xcodeproj
** BUILD FAILED **
The following build commands failed:
	Check dependencies
(1 failure)
** ARCHIVE FAILED **

when i tried this line $ ipa  build --embed "iOS Team Provisioning Profile" --verbose 

after build i got this **ARACHIVE FAILED** in red color  without error message 

please help 

so i don't know how to create know conversation here 
thanks

**Pull request merged**
