### PR TITLE
Print public urls of files uploaded to S3

### PR DESCRIPTION
**Pull request by joshdholtz**
Adds the public url of the uploaded files to the output of the `distribute:s3` command. Going to use this for an integration for "fastlane" (https://github.com/KrauseFx/fastlane) but also just nice to see after running the `distribute:s3` command.

## Sample Output
```sh
$: ipa distrubute:s3 -f MyApp.ipa -d MyApp.app.dSYM.zip -b your-bucket -a shhh -s super-shhh
https://your-bucket.s3.amazonaws.com/MyApp.ipa
https://your-bucket.s3.amazonaws.com/MyApp.app.dSYM.zip
Build successfully uploaded to S3
```

### CODE REVIEW

**Comment by alistra** [comment]
+1

**Comment by KrauseFx** [comment]
No merging of this pull request @mattt? Do you have security concerns? If so, we could also add a flag or environment variable to skip generating of public URLs.

**Comment by joshdholtz** [comment]
Is there anything against this PR or holding back from this PR getting merged in?

**Comment by mattt** [comment]
Thanks @joshdholtz. Apologies for not merging sooner. The previous release of Shenzhen was a patch release, focused on a few specific bugfixes. This will be live soon in the forthcoming release.

**Comment by joshdholtz** [comment]
@mattt No problem at all! I know how it goes :grin: Just wanted to make sure there weren't any additional changes I needed to make

**Pull request merged**
