### PR TITLE
building ipa failed with Xcode 8.3

### PR DESCRIPTION
**Pull request by checkolala**
From Xcode 8.3 “xrun PackageApplication” is removed and must replaced by xcodebuild --exportArchive ...

### CODE REVIEW

**Comment by dankimio** [comment]
@bender75 Thank you for the pull request! I'll review it soon.

**Comment by KrauseFx** [comment]
I'd strongly recommend checkout out [gym](https://fastlane.tools/gym) which uses the latest Xcode API to build and archive your app. It was inspired by `shenzhen`, and is very actively being developed as part of [fastlane](https://fastlane.tools). It's used by thousands of companies and includes patches for all kinds of edge cases around code signing with the new Xcode export API 👍

**Comment by jackyzonewen** [comment]
@bender75 i had clone your branch, then gem build and gem install the local gem package, bug when i exec "ipa build" to build my app, it can't generate ipa in folder but in console it print success generate xxxx.ipa. thanks

**Comment by LiuXingCode** [comment]
@bender75  Thank you very much for your timely help, great, I have been able to successfully packaged!

**Comment by bender75** [comment]
@jackyzonewen : please review the two new build params! You need to provide a archivepath and a export option plist

**Comment by bender75** [comment]
@KrauseFix gym looks like a charm. Thank you very much for your tip

**Comment by LiuXingCode** [comment]
@bender75  I changed the **build.rb** file, the use of **jenkins** package upload to PGYER, reported the following error, I found and did not generate ipa file, hope to be resolved as soon as possible, thank you!

```
[weibo] $ /bin/sh -xe /var/folders/cf/w6t40mxs5v3422sjkgq16zvr0000gn/T/hudson6034224794690466323.sh
+ ipa build
[31mNo schemes found in Xcode project or workspace[0m
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Pull request closed without merging**
